version: "3.9"

services:
  core:
    container_name: core
    build:
      context: ./flask
      target: development
      dockerfile: ./Dockerfile
      args:
        - NAME=${NAME}
    volumes:
      - ./flask:/core
