version: "3.9"

services:
  core:
    container_name: core
    build: 
      context: ./flask
      target: development
      dockerfile: ./Dockerfile
      args:
        - NAME=${NAME}
    ports:
      - 5000:5000
    volumes:
      - ./flask:/core
