version: "3.9"

services:
  core:
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql:///postgres@postgres:postgres:5432/postgres"
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
