version: "3.9"

services:
  core:
    container_name: core
    build:
      context: ./core
      target: development
      dockerfile: ./Dockerfile
      args:
        - NAME=${NAME}
    volumes:
      - ./core:/core
